version: '3'
services:
  wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=root
     - WORDPRESS_DB_USER=root
    ports:
     - '9000:9000'
    volumes:
     - ./wordpress:/var/www/html
  mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
     - '80:80'
     - '443:443'
    depends_on:
     - wordpress
    restart: always
    volumes:
     - ./nginx:/etc/nginx/conf.d
     - ./logs/nginx:/var/log/nginx
     - ./wordpress:/var/www/html
    links:
     - wordpress