version: '3'

services:

  frontend:
    image: bgdshka/itmo-projects
    depends_on:
      - "nginx-proxy"
    expose:
      - "3000"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "3000:80"
      - "443:443"
      - "80:80"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
